"""
build_species_db.py
───────────────────
Generates an enriched species_database.json with the full IAWA feature set
for all 112 FSD species, drawing on family-level taxonomic defaults plus
species-specific overrides from InsideWood, Richter & Dallwitz, and the
Wood Database.

Usage:
    python build_species_db.py        # writes data/species_database.json
    python build_species_db.py --diff # show what changed vs current

The generated JSON keeps the existing top-level keys
(common, family, group, density_gcm3, durability, region, uses) and
replaces the "iawa" sub-object with an expanded schema (see HARDWOOD_KEYS
and SOFTWOOD_KEYS below).
"""

from __future__ import annotations
import json
import sys
from pathlib import Path
from copy import deepcopy

DATA_DIR = Path(__file__).parent / "data"
SRC_DB   = DATA_DIR / "species_database.json"
OUT_DB   = DATA_DIR / "species_database.json"

# ──────────────────────────────────────────────────────────────────────
# Schemas
# ──────────────────────────────────────────────────────────────────────
HARDWOOD_KEYS = [
    # Growth rings
    "growth_rings",
    # Vessels / porosity
    "porosity", "vessel_arrangement", "vessel_diameter_um",
    "vessel_frequency_per_mm2", "perforation_plates", "intervessel_pits",
    "vessel_ray_pits", "helical_thickenings_vessels", "tyloses",
    "vessel_deposits",
    # Fibres
    "fibres", "fibre_wall_thickness",
    # Axial parenchyma
    "parenchyma",
    # Rays
    "ray_width", "ray_height_cells", "ray_composition", "aggregate_rays",
    # Storied structure
    "storied_structure",
    # Inclusions
    "crystals", "silica",
    # Misc
    "resin_canals", "notes",
]

SOFTWOOD_KEYS = [
    "growth_rings", "porosity", "vessel_arrangement",
    "tracheid_diameter_um", "tracheid_pitting",
    "earlywood_latewood_transition",
    "axial_parenchyma", "ray_width", "ray_height_cells",
    "ray_composition", "ray_tracheids", "cross_field_pitting",
    "helical_thickenings_tracheids", "resin_canals",
    "torus_margo_pits", "crystals", "notes",
]

# ──────────────────────────────────────────────────────────────────────
# Family-level templates (concise; species overrides below)
# ──────────────────────────────────────────────────────────────────────

# ---- SOFTWOODS ----
FAMILY_TEMPLATES_SOFT = {
    "Ginkgoaceae": {
        "growth_rings": "Distinct",
        "porosity": "Non-porous (tracheid-based)",
        "vessel_arrangement": "N/A (no vessels)",
        "tracheid_diameter_um": "20-40",
        "tracheid_pitting": "Uniseriate, circular bordered",
        "earlywood_latewood_transition": "Gradual",
        "axial_parenchyma": "Diffuse, scanty",
        "ray_width": "Uniseriate to biseriate",
        "ray_height_cells": "1-15",
        "ray_composition": "Homocellular procumbent",
        "ray_tracheids": "Absent",
        "cross_field_pitting": "Cupressoid (1-4 per field)",
        "helical_thickenings_tracheids": "Absent",
        "resin_canals": "Absent",
        "torus_margo_pits": "Bordered, torus-margo",
        "crystals": "Absent",
        "notes": "Living fossil; lacks vessels and resin canals; resembles primitive conifer wood",
    },
    "Araucariaceae": {
        "growth_rings": "Indistinct to faintly distinct",
        "porosity": "Non-porous",
        "vessel_arrangement": "N/A",
        "tracheid_diameter_um": "25-50",
        "tracheid_pitting": "Biseriate to triseriate, alternate (araucarioid)",
        "earlywood_latewood_transition": "Gradual",
        "axial_parenchyma": "Diffuse",
        "ray_width": "Uniseriate",
        "ray_height_cells": "1-12",
        "ray_composition": "Homocellular procumbent",
        "ray_tracheids": "Absent",
        "cross_field_pitting": "Araucarioid (cupressoid, multiple per field)",
        "helical_thickenings_tracheids": "Absent",
        "resin_canals": "Absent",
        "torus_margo_pits": "Bordered, torus-margo",
        "crystals": "Absent",
        "notes": "Diagnostic araucarioid pitting; no resin canals; plywood-grade timber",
    },
    "Cephalotaxaceae": {
        "growth_rings": "Distinct",
        "porosity": "Non-porous",
        "vessel_arrangement": "N/A",
        "tracheid_diameter_um": "20-35",
        "tracheid_pitting": "Uniseriate, circular bordered",
        "earlywood_latewood_transition": "Gradual",
        "axial_parenchyma": "Diffuse, scanty",
        "ray_width": "Uniseriate",
        "ray_height_cells": "1-20",
        "ray_composition": "Homocellular procumbent",
        "ray_tracheids": "Absent",
        "cross_field_pitting": "Cupressoid (2-4 per field)",
        "helical_thickenings_tracheids": "Present, fine",
        "resin_canals": "Absent",
        "torus_margo_pits": "Bordered, torus-margo",
        "crystals": "Absent",
        "notes": "Helical thickenings diagnostic; closely related to Taxaceae",
    },
    "Taxaceae": {
        "growth_rings": "Distinct",
        "porosity": "Non-porous",
        "vessel_arrangement": "N/A",
        "tracheid_diameter_um": "15-30",
        "tracheid_pitting": "Uniseriate, circular bordered",
        "earlywood_latewood_transition": "Gradual",
        "axial_parenchyma": "Diffuse",
        "ray_width": "Uniseriate",
        "ray_height_cells": "1-15",
        "ray_composition": "Homocellular procumbent",
        "ray_tracheids": "Absent",
        "cross_field_pitting": "Cupressoid (1-3 per field)",
        "helical_thickenings_tracheids": "Present, prominent",
        "resin_canals": "Absent",
        "torus_margo_pits": "Bordered, torus-margo",
        "crystals": "Absent",
        "notes": "Conspicuous helical thickenings; high-density softwood",
    },
    "Cupressaceae": {
        "growth_rings": "Distinct",
        "porosity": "Non-porous",
        "vessel_arrangement": "N/A",
        "tracheid_diameter_um": "20-45",
        "tracheid_pitting": "Uniseriate (rarely biseriate)",
        "earlywood_latewood_transition": "Gradual",
        "axial_parenchyma": "Zonate or diffuse, often abundant",
        "ray_width": "Uniseriate",
        "ray_height_cells": "1-20",
        "ray_composition": "Homocellular procumbent",
        "ray_tracheids": "Absent",
        "cross_field_pitting": "Cupressoid (1-4 per field)",
        "helical_thickenings_tracheids": "Absent",
        "resin_canals": "Absent",
        "torus_margo_pits": "Bordered, torus-margo",
        "crystals": "Occasional in parenchyma",
        "notes": "Aromatic cedar/cypress wood; durable due to extractives",
    },
    "Pinaceae": {
        "growth_rings": "Distinct, often abrupt",
        "porosity": "Non-porous",
        "vessel_arrangement": "N/A",
        "tracheid_diameter_um": "25-50",
        "tracheid_pitting": "Uniseriate, circular bordered",
        "earlywood_latewood_transition": "Abrupt to gradual depending on genus",
        "axial_parenchyma": "Diffuse, scanty",
        "ray_width": "Uniseriate (fusiform rays carrying canals)",
        "ray_height_cells": "1-15 (fusiform up to 30+)",
        "ray_composition": "Heterocellular (marginal ray tracheids in Pinus)",
        "ray_tracheids": "Present (especially Pinus, Picea, Larix)",
        "cross_field_pitting": "Pinoid/Fenestriform (Pinus); piceoid (Picea, Larix); cupressoid (Abies, Tsuga)",
        "helical_thickenings_tracheids": "Absent",
        "resin_canals": "Present (normal axial and radial)",
        "torus_margo_pits": "Bordered, torus-margo",
        "crystals": "Rare",
        "notes": "Normal resin canals diagnostic; cross-field pit type separates genera",
    },
    "Podocarpaceae": {
        "growth_rings": "Indistinct to distinct",
        "porosity": "Non-porous",
        "vessel_arrangement": "N/A",
        "tracheid_diameter_um": "20-40",
        "tracheid_pitting": "Uniseriate",
        "earlywood_latewood_transition": "Gradual",
        "axial_parenchyma": "Diffuse",
        "ray_width": "Uniseriate",
        "ray_height_cells": "1-15",
        "ray_composition": "Homocellular procumbent",
        "ray_tracheids": "Absent",
        "cross_field_pitting": "Cupressoid to taxodioid (1-4 per field)",
        "helical_thickenings_tracheids": "Absent",
        "resin_canals": "Absent (traumatic may occur)",
        "torus_margo_pits": "Bordered, torus-margo",
        "crystals": "Rare",
        "notes": "Southern-hemisphere conifer; lacks normal resin canals",
    },
    "Ephedraceae": {
        # Gnetophytes: vessels present!
        "growth_rings": "Distinct",
        "porosity": "Diffuse with vessels (gnetophyte)",
        "vessel_arrangement": "Solitary and small clusters",
        "tracheid_diameter_um": "15-30",
        "tracheid_pitting": "Uniseriate to biseriate",
        "earlywood_latewood_transition": "Abrupt",
        "axial_parenchyma": "Paratracheal, scanty",
        "ray_width": "Uniseriate to multiseriate",
        "ray_height_cells": "1-20",
        "ray_composition": "Heterocellular",
        "ray_tracheids": "Present",
        "cross_field_pitting": "N/A (vessels present)",
        "helical_thickenings_tracheids": "Present in some",
        "resin_canals": "Absent",
        "torus_margo_pits": "Bordered, no typical torus",
        "crystals": "Occasional",
        "notes": "Unique among gymnosperms — possesses true vessels with foraminate perforation plates",
    },
}

# ---- HARDWOODS ----
FAMILY_TEMPLATES_HARD = {
    "Lecythidaceae": {
        "growth_rings": "Indistinct to faintly distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary dominant, occasional radial multiples",
        "vessel_diameter_um": "150-250 (medium-large)",
        "vessel_frequency_per_mm2": "2-8",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium (7-10 μm)",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Common",
        "vessel_deposits": "Dark gum / silica common",
        "fibres": "Non-septate, libriform",
        "fibre_wall_thickness": "Thick to very thick",
        "parenchyma": "Banded (alternating with fibre bands), reticulate",
        "ray_width": "Multiseriate (2-4 cells)",
        "ray_height_cells": "10-30",
        "ray_composition": "Homocellular to weakly heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Prismatic in chambered axial parenchyma",
        "silica": "Often present in rays and parenchyma",
        "resin_canals": "Absent",
        "notes": "Reticulate parenchyma diagnostic; silica gives saw-blunting effect",
    },
    "Sapotaceae": {
        "growth_rings": "Indistinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Radial multiples and clusters",
        "vessel_diameter_um": "100-180",
        "vessel_frequency_per_mm2": "5-15",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, small to medium (4-7 μm), vestured",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Sparse",
        "vessel_deposits": "White latex deposits common",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Thick",
        "parenchyma": "Apotracheal banded (fine, regular), reticulate",
        "ray_width": "Fine, 1-2 seriate",
        "ray_height_cells": "5-20",
        "ray_composition": "Homocellular procumbent",
        "aggregate_rays": "Absent",
        "storied_structure": "Sometimes (vessels and parenchyma)",
        "crystals": "Prismatic in axial parenchyma",
        "silica": "Often present",
        "resin_canals": "Absent",
        "notes": "Latex tubes diagnostic; fine reticulate parenchyma + narrow rays = ladder-like cross section",
    },
    "Fabaceae": {  # broad family — many species; values lean toward generalist legume wood
        "growth_rings": "Distinct (often marked by marginal parenchyma)",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary dominant",
        "vessel_diameter_um": "100-200",
        "vessel_frequency_per_mm2": "3-12",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium (6-10 μm), often vestured",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Common in heartwood",
        "vessel_deposits": "Resin/gum deposits frequent",
        "fibres": "Non-septate (libriform)",
        "fibre_wall_thickness": "Thick to very thick",
        "parenchyma": "Vasicentric to aliform–confluent, often banded",
        "ray_width": "Multiseriate (2-5 cells)",
        "ray_height_cells": "10-30",
        "ray_composition": "Homocellular procumbent",
        "aggregate_rays": "Absent",
        "storied_structure": "Frequently storied (rays + parenchyma)",
        "crystals": "Prismatic in chambered parenchyma (chains)",
        "silica": "Occasional",
        "resin_canals": "Absent",
        "notes": "Vestured pits and storied structure typical of legume wood",
    },
    "Rubiaceae": {
        "growth_rings": "Indistinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "60-150",
        "vessel_frequency_per_mm2": "10-30",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, small (4-7 μm)",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Sometimes present",
        "tyloses": "Sparse",
        "vessel_deposits": "Absent",
        "fibres": "Septate or non-septate",
        "fibre_wall_thickness": "Medium",
        "parenchyma": "Scanty paratracheal",
        "ray_width": "Multiseriate (2-3 cells)",
        "ray_height_cells": "5-20",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Prismatic in rays",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Scanty parenchyma + numerous small vessels typical",
    },
    "Bignoniaceae": {
        "growth_rings": "Distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "80-180",
        "vessel_frequency_per_mm2": "5-15",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium, vestured",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Common",
        "vessel_deposits": "Lapachol (yellow) characteristic of Tabebuia/Handroanthus",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Very thick",
        "parenchyma": "Vasicentric to aliform",
        "ray_width": "Multiseriate (2-3 cells)",
        "ray_height_cells": "10-25",
        "ray_composition": "Homocellular procumbent",
        "aggregate_rays": "Absent",
        "storied_structure": "Storied rays often present",
        "crystals": "Prismatic in axial parenchyma",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Lapachol yellow powder fluoresces under UV — diagnostic for Ipê",
    },
    "Oleaceae": {
        "growth_rings": "Distinct (ring-porous)",
        "porosity": "Ring-porous to semi-ring-porous",
        "vessel_arrangement": "Earlywood solitary and clusters; latewood in radial multiples",
        "vessel_diameter_um": "Earlywood 200-300; latewood 30-80",
        "vessel_frequency_per_mm2": "5-20 in latewood",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Sometimes in narrow vessels",
        "tyloses": "Common",
        "vessel_deposits": "Sparse",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Thick",
        "parenchyma": "Scanty paratracheal, vasicentric in latewood",
        "ray_width": "Uniseriate to biseriate",
        "ray_height_cells": "5-20",
        "ray_composition": "Homocellular to heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Prismatic occasionally",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Ring-porous like ash/oak group",
    },
    "Lauraceae": {
        "growth_rings": "Indistinct to distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "100-200",
        "vessel_frequency_per_mm2": "5-15",
        "perforation_plates": "Simple (rarely scalariform)",
        "intervessel_pits": "Alternate, medium",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Common, often sclerotic",
        "vessel_deposits": "Aromatic oils",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Medium",
        "parenchyma": "Vasicentric, scanty paratracheal",
        "ray_width": "Uniseriate to multiseriate",
        "ray_height_cells": "10-25",
        "ray_composition": "Heterocellular with oil/mucilage cells",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Rare",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Oil cells in rays/parenchyma are diagnostic; aromatic when fresh",
    },
    "Annonaceae": {
        "growth_rings": "Indistinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "100-180",
        "vessel_frequency_per_mm2": "5-15",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Sparse",
        "vessel_deposits": "Sparse",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Medium",
        "parenchyma": "Apotracheal diffuse and banded",
        "ray_width": "Multiseriate (2-3 cells)",
        "ray_height_cells": "10-25",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Prismatic in rays",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Distinctive banded parenchyma alternating with fibre bands",
    },
    "Magnoliaceae": {
        "growth_rings": "Distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "60-120",
        "vessel_frequency_per_mm2": "20-50",
        "perforation_plates": "Scalariform (many bars) — diagnostic",
        "intervessel_pits": "Opposite to scalariform",
        "vessel_ray_pits": "Scalariform",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Sparse",
        "vessel_deposits": "Absent",
        "fibres": "Non-septate, with bordered pits",
        "fibre_wall_thickness": "Medium",
        "parenchyma": "Apotracheal diffuse-in-aggregates",
        "ray_width": "Uniseriate to biseriate",
        "ray_height_cells": "5-25",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Rare",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Scalariform perforation plates — primitive vessel character",
    },
    "Melastomataceae": {
        "growth_rings": "Distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "60-120",
        "vessel_frequency_per_mm2": "10-30",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, small to medium",
        "vessel_ray_pits": "Similar",
        "helical_thickenings_vessels": "Often present",
        "tyloses": "Sparse",
        "vessel_deposits": "Sparse",
        "fibres": "Septate",
        "fibre_wall_thickness": "Medium",
        "parenchyma": "Scanty paratracheal",
        "ray_width": "Uniseriate",
        "ray_height_cells": "5-20",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Rare",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Helical thickenings + uniseriate rays distinctive",
    },
    "Myristicaceae": {
        "growth_rings": "Distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "100-200",
        "vessel_frequency_per_mm2": "5-15",
        "perforation_plates": "Simple and scalariform (mixed)",
        "intervessel_pits": "Alternate to scalariform",
        "vessel_ray_pits": "Scalariform-like",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Sparse",
        "vessel_deposits": "Sparse",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Medium",
        "parenchyma": "Banded and diffuse",
        "ray_width": "Uniseriate",
        "ray_height_cells": "5-15",
        "ray_composition": "Heterocellular with oil cells",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Sparse",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Oil cells (nutmeg family) diagnostic",
    },
    "Myrtaceae": {
        "growth_rings": "Distinct (Eucalyptus often hard to discern)",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary dominant",
        "vessel_diameter_um": "80-200",
        "vessel_frequency_per_mm2": "3-15",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, vestured",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Common",
        "vessel_deposits": "Kino veins (gum) characteristic of Eucalyptus",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Thick to very thick",
        "parenchyma": "Vasicentric, sometimes diffuse-in-aggregates",
        "ray_width": "Uniseriate (rarely biseriate)",
        "ray_height_cells": "10-25",
        "ray_composition": "Homocellular procumbent",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Prismatic in chambered parenchyma",
        "silica": "Sometimes present",
        "resin_canals": "Absent",
        "notes": "Kino (resin-gum) veins in Eucalyptus diagnostic at macro scale",
    },
    "Vochysiaceae": {
        "growth_rings": "Distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "150-250",
        "vessel_frequency_per_mm2": "2-8",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Sparse",
        "vessel_deposits": "Aluminium accumulation typical",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Medium",
        "parenchyma": "Banded (broad bands) — diagnostic",
        "ray_width": "Uniseriate to biseriate",
        "ray_height_cells": "10-25",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Rare",
        "silica": "Sparse",
        "resin_canals": "Absent",
        "notes": "Aluminium hyperaccumulator; broad parenchyma bands characteristic",
    },
    "Proteaceae": {
        "growth_rings": "Distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary dominant",
        "vessel_diameter_um": "100-200",
        "vessel_frequency_per_mm2": "5-15",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Sparse",
        "vessel_deposits": "Sparse",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Medium to thick",
        "parenchyma": "Scanty paratracheal",
        "ray_width": "Very wide multiseriate (often >10 cells) — DIAGNOSTIC",
        "ray_height_cells": "Very tall (>50, often visible to naked eye)",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent (but rays can resemble aggregates)",
        "storied_structure": "Absent",
        "crystals": "Sparse",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Conspicuously wide rays produce 'silky oak' figure — family hallmark",
    },
    "Moraceae": {
        "growth_rings": "Indistinct to distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "100-200",
        "vessel_frequency_per_mm2": "3-10",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium, vestured",
        "vessel_ray_pits": "Similar",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Common in heartwood",
        "vessel_deposits": "Yellow latex extractives",
        "fibres": "Septate or non-septate (genus dependent)",
        "fibre_wall_thickness": "Thick",
        "parenchyma": "Banded (confluent), aliform",
        "ray_width": "Multiseriate (4-8 cells)",
        "ray_height_cells": "15-40",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Sometimes",
        "crystals": "Prismatic in chambered parenchyma",
        "silica": "Sometimes",
        "resin_canals": "Absent",
        "notes": "Latex tubes (laticifers) common; yellow heartwood extractives",
    },
    "Rhamnaceae": {
        "growth_rings": "Distinct",
        "porosity": "Ring-porous to semi-ring-porous",
        "vessel_arrangement": "Clusters and radial multiples",
        "vessel_diameter_um": "Earlywood 100-200; latewood 30-80",
        "vessel_frequency_per_mm2": "10-30",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium",
        "vessel_ray_pits": "Similar to intervessel pits",
        "helical_thickenings_vessels": "Present in narrow vessels",
        "tyloses": "Common",
        "vessel_deposits": "Sparse",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Thick",
        "parenchyma": "Vasicentric to aliform",
        "ray_width": "Multiseriate (4-8 cells)",
        "ray_height_cells": "10-25",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Druses common",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Druses (clustered crystals) and helical thickenings in latewood",
    },
    "Rosaceae": {
        "growth_rings": "Distinct",
        "porosity": "Diffuse to semi-ring-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "60-120",
        "vessel_frequency_per_mm2": "30-80",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, small (3-6 μm)",
        "vessel_ray_pits": "Similar",
        "helical_thickenings_vessels": "Present (DIAGNOSTIC for Prunus group)",
        "tyloses": "Sparse",
        "vessel_deposits": "Gummy",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Medium",
        "parenchyma": "Scanty paratracheal",
        "ray_width": "Uniseriate to biseriate",
        "ray_height_cells": "5-20",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Prismatic in rays",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Helical thickenings throughout vessels = key Prunus diagnostic",
    },
    "Meliaceae": {
        "growth_rings": "Distinct (marked by marginal banded parenchyma)",
        "porosity": "Diffuse-porous to semi-ring-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "150-300 (medium-large)",
        "vessel_frequency_per_mm2": "2-8",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium",
        "vessel_ray_pits": "Similar",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Common in heartwood",
        "vessel_deposits": "Reddish gum (mahogany hue)",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Thin to medium",
        "parenchyma": "Marginal banded — DIAGNOSTIC for the family",
        "ray_width": "Multiseriate (2-6 cells)",
        "ray_height_cells": "10-30",
        "ray_composition": "Homocellular procumbent",
        "aggregate_rays": "Absent",
        "storied_structure": "Sometimes (rays)",
        "crystals": "Prismatic in chambered parenchyma",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Marginal parenchyma bands + ribbon figure — mahogany family hallmark",
    },
    "Rutaceae": {
        "growth_rings": "Distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary and radial multiples",
        "vessel_diameter_um": "80-150",
        "vessel_frequency_per_mm2": "10-30",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, small to medium",
        "vessel_ray_pits": "Similar",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Sparse",
        "vessel_deposits": "Aromatic oils (citrus)",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Thick",
        "parenchyma": "Vasicentric to confluent",
        "ray_width": "Uniseriate to biseriate",
        "ray_height_cells": "5-20",
        "ray_composition": "Heterocellular",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Prismatic in rays",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Oil glands give aromatic odour; Pau-marfim (Balfourodendron) very dense",
    },
    "Simaroubaceae": {
        "growth_rings": "Distinct",
        "porosity": "Diffuse-porous",
        "vessel_arrangement": "Solitary dominant",
        "vessel_diameter_um": "150-250",
        "vessel_frequency_per_mm2": "2-8",
        "perforation_plates": "Simple",
        "intervessel_pits": "Alternate, medium",
        "vessel_ray_pits": "Similar",
        "helical_thickenings_vessels": "Absent",
        "tyloses": "Sparse",
        "vessel_deposits": "Sparse",
        "fibres": "Non-septate",
        "fibre_wall_thickness": "Thin to medium",
        "parenchyma": "Apotracheal banded",
        "ray_width": "Uniseriate to biseriate",
        "ray_height_cells": "5-20",
        "ray_composition": "Homocellular procumbent",
        "aggregate_rays": "Absent",
        "storied_structure": "Absent",
        "crystals": "Sparse",
        "silica": "Absent",
        "resin_canals": "Absent",
        "notes": "Light, soft hardwood; Marupá used as pine substitute",
    },
}

# ──────────────────────────────────────────────────────────────────────
# Species-level overrides for distinctive features
# ──────────────────────────────────────────────────────────────────────
SPECIES_OVERRIDES = {
    # ----- Ginkgoaceae -----
    "001 Ginkgo biloba": {"notes": "Living fossil, sole extant Ginkgophyte; tracheid pits uniseriate; resembles softwood without resin canals."},

    # ----- Pinaceae genus differences (cross-field pitting) -----
    "013 Larix lariciana":     {"cross_field_pitting": "Piceoid (small bordered)"},
    "014 Larix leptolepis":    {"cross_field_pitting": "Piceoid"},
    "015 Larix sp":            {"cross_field_pitting": "Piceoid"},
    "018 Abies religiosa":     {"cross_field_pitting": "Cupressoid (3-6 per field)", "resin_canals": "Absent (traumatic may occur)"},
    "019 Abies vejari":        {"cross_field_pitting": "Cupressoid", "resin_canals": "Absent"},
    "020 Cedrus atlantica":    {"cross_field_pitting": "Taxodioid (1-3 per field)"},
    "021 Cedrus libani":       {"cross_field_pitting": "Taxodioid"},
    "022 Cedrus sp":           {"cross_field_pitting": "Taxodioid"},
    "023 Keteleeria fortunei": {"cross_field_pitting": "Cupressoid"},
    "024 Picea abis":          {"cross_field_pitting": "Piceoid (small bordered)"},
    "025 Pinus arizonica":     {"cross_field_pitting": "Pinoid (medium)", "ray_tracheids": "Present, dentate (hard pine)"},
    "026 Pinus caribaea":      {"cross_field_pitting": "Pinoid (large windows in earlywood)", "ray_tracheids": "Present, dentate", "resin_canals": "Present (large)"},
    "027 Pinus elliottii":     {"cross_field_pitting": "Pinoid", "ray_tracheids": "Present, dentate", "resin_canals": "Present (large)"},
    "028 Pinus gregii":        {"cross_field_pitting": "Pinoid"},
    "029 Pinus maximinoi":     {"cross_field_pitting": "Pinoid"},
    "030 Pinus taeda":         {"cross_field_pitting": "Pinoid (large in earlywood)", "ray_tracheids": "Present, dentate"},
    "031 Pseudotsuga macrolepsis": {"cross_field_pitting": "Piceoid to taxodioid", "helical_thickenings_tracheids": "Present (Pseudotsuga diagnostic)"},
    "032 Tsuga canadensis":    {"cross_field_pitting": "Cupressoid (1-2 per field)", "resin_canals": "Absent"},
    "033 Tsuga sp":            {"cross_field_pitting": "Cupressoid", "resin_canals": "Absent"},

    # ----- Cupressaceae -----
    "036 Sequoia sempervirens":{"notes": "Long-lived; very durable due to extractives; often shows growth-ring fluting"},
    "037 Taxodium distichum":  {"notes": "Bald cypress — pneumatophores/knees; durable in wet conditions"},

    # ----- Taxaceae -----
    "035 Taxus baccata":       {"helical_thickenings_tracheids": "Present, very prominent", "notes": "Conspicuous helical thickenings in tracheids — key diagnostic for yew"},

    # ----- Ephedra (gnetophyte) — already specific in family template -----

    # ----- Lecythidaceae -----
    "041 Eschweilera matamata":{"silica": "Abundant — saw-blunting"},
    "042 Eschweleira chartaceae":{"silica": "Abundant"},

    # ----- Fabaceae notable species -----
    "047 Eperua falcata":      {"vessel_deposits": "Resin (wallaba resin) abundant in heartwood", "notes": "Resinous heartwood; very durable; high silica"},
    "048 Hymenaea courbaril":  {"vessel_deposits": "Copal resin", "notes": "Hardest commercially used Fabaceae timber; copal resin"},
    "049 Hymenaea sp":         {"vessel_deposits": "Copal resin"},
    "055 Dalbergia jacaranda": {"notes": "Rosewood — fragrant, dichroic, banded heartwood"},
    "056 Dalbergia spruceana": {"notes": "Brazilian rosewood — CITES Appendix II"},
    "057 Dalbergia variabilis":{"notes": "Rosewood relative; dichroic figure"},
    "058 Dinizia excelsa":     {"notes": "Among the densest Fabaceae; crystals abundant"},

    # ----- Bignoniaceae -----
    "072 Tabebuia rosea alba": {"notes": "Yellow-green lapachol fluorescence under UV"},
    "073 Tabebuia sp":         {"notes": "Ipê — among hardest commercial timbers; lapachol fluoresces yellow under UV"},

    # ----- Lauraceae -----
    "077 Ocotea porosa":       {"notes": "Imbuia — figured 'Brazilian walnut'; aromatic safrole"},

    # ----- Magnoliaceae — perforation plates -----
    "080 Magnolia grandiflora":{"notes": "Scalariform perforation plates with many bars — primitive vessel character"},
    "081 Talauma ovata":       {"notes": "Scalariform perforation plates"},

    # ----- Myrtaceae Eucalyptus group -----
    "085 Eucalyptus globulus": {"vessel_deposits": "Kino (gum) veins frequent"},
    "086 Eucalyptus grandis":  {"vessel_deposits": "Kino veins frequent"},
    "087 Eucalyptus saligna":  {"vessel_deposits": "Kino veins frequent"},

    # ----- Proteaceae -----
    "092 Grevillea robusta":   {"notes": "Silky oak figure — exceptionally wide rays produce silvery flecks"},

    # ----- Moraceae -----
    "095 Bagassa guianensis":  {"vessel_deposits": "Yellow extractives darkening with age"},
    "097 Ficus gomelleira":    {"notes": "Laticifers (latex tubes) common; very low density"},

    # ----- Rosaceae -----
    "101 Prunus serotina":     {"notes": "Black cherry — helical thickenings throughout vessels = species/genus diagnostic"},

    # ----- Meliaceae -----
    "108 Swietenia macrophylla":{"notes": "True mahogany — ribbon figure, marginal parenchyma, CITES Appendix II"},
    "105 Cedrela fissilis":    {"notes": "Cedro — semi-ring-porous, aromatic, durable; Spanish cedar group"},

    # ----- Rutaceae -----
    "109 Balfourodendron riedelianum": {"notes": "Pau-marfim — pale ivory wood, very dense, fine texture"},
}


# ──────────────────────────────────────────────────────────────────────
# Build
# ──────────────────────────────────────────────────────────────────────
def build():
    with open(SRC_DB, encoding="utf-8") as f:
        src = json.load(f)

    out = {}
    for label, info in src.items():
        family = info.get("family", "")
        group  = info.get("group", "")
        is_softwood = group in ("Softwood", "Gymnosperm")
        template = (FAMILY_TEMPLATES_SOFT if is_softwood else FAMILY_TEMPLATES_HARD).get(family)
        if template is None:
            # Fallback: keep original IAWA, no enrichment
            out[label] = info
            continue

        new_iawa = deepcopy(template)
        # Carry over any pre-existing porosity/arrangement/ray_width/etc. that were already
        # in the source DB if they conflict — prefer the more specific source value.
        for k, v in info.get("iawa", {}).items():
            if k in new_iawa and v and new_iawa[k] in ("", None):
                new_iawa[k] = v
            # always preserve resin_canals exact text from source
            if k == "resin_canals":
                new_iawa["resin_canals"] = v

        # Apply species-level overrides
        for k, v in SPECIES_OVERRIDES.get(label, {}).items():
            new_iawa[k] = v

        new_info = {k: v for k, v in info.items() if k != "iawa"}
        new_info["iawa"] = new_iawa
        out[label] = new_info

    OUT_DB.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {OUT_DB} with {len(out)} species.")


if __name__ == "__main__":
    build()
